//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentBoat1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public int BId { get; set; }
        public string BNo { get; set; }
        public string Availability { get; set; }
        public string BImage { get; set; }
    }
}
